name: pull request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  format:
    name: "format"
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22.22.3
          cache: npm
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
      - name: install npm dependencies
        run: npm ci
      - name: check formatting
        run: npm run test:fmt

  test:
    name: "test"
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: check out repo
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22.22.3
          cache: npm
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
      - name: install npm dependencies
        run: npm ci
      - name: run type checks
        run: npm run test:types
      - name: run linter
        run: npm run test:lint
      - name: run unit tests
        run: npm run test:unit
      - name: build package
        run: npm run build
      - name: build docs
        run: npm run docs:build
